CREATE TABLE "contentForPreferences" (
	"Id"	INTEGER,
	"IdContent"	INTEGER NOT NULL,
	"IdUsers"	INTEGER NOT NULL,
	FOREIGN KEY("IdUsers") REFERENCES "users"("Id") ON DELETE CASCADE,
	FOREIGN KEY("IdContent") REFERENCES "content"("Id") ON DELETE CASCADE,
	PRIMARY KEY("Id" AUTOINCREMENT)
)