CREATE TABLE "history" (
	"Id"	INTEGER,
	"IdUser"	INTEGER NOT NULL,
	"IdContent"	INTEGER NOT NULL,
	"EndSee"	INTEGER NOT NULL,
	FOREIGN KEY("IdContent") REFERENCES "content"("Id") ON DELETE CASCADE,
	FOREIGN KEY("IdUser") REFERENCES "users"("Id") ON DELETE CASCADE,
	PRIMARY KEY("Id" AUTOINCREMENT)
)